### ISSUE TITLE
Issue with _json

### ISSUE THREAD

**Issue by guillain** [StackStorm-Exchange/stackstorm-cisco_spark#4]
Hi,

Thanks a lot for this pack.
Unfortunately I've a issue with the script "/opt/stackstorm/packs/cisco_spark/actions/generic_action.py" in line 18 caused by the json return.
If I don't remove the "_json", I've an error in the feedback.
But in both cases it works (ie room creation is ok).

log
```
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 278, in <module>
    obj.run()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2common/runners/python_action_wrapper.py", line 171, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/cisco_spark/actions/generic_action.py", line 18, in run
    return result._json  # pylint: disable=no-member
  File "/opt/stackstorm/virtualenvs/cisco_spark/lib/python2.7/site-packages/ciscosparkapi/sparkdata.py", line 112, in __getattr__
    raise AttributeError(error)
AttributeError: 'Room' object has no attribute '_json'
```

Thanks for your support and dev!

**Comment by LindsayHill** [comment]
Thanks for the bug report. Could you confirm which action you're running that generates the error? Is it `cisco_spark.create_room`?

I guess maybe some of the methods don't return any `_json`. Would need to check the Cisco Spark API docs.

**Comment by tonybaloney** [comment]
looks like the internal class fields have changed 

https://github.com/CiscoDevNet/ciscosparkapi/blame/master/ciscosparkapi/sparkdata.py#L127 

Will update the reference

**Comment by tonybaloney** [comment]
@guillain fixed in https://github.com/StackStorm-Exchange/stackstorm-cisco_spark/pull/5 please can you check this works for you.

**Comment by guillain** [comment]
Hi Tony,

Thanks a lot for your reactivity and the fix that works well!

Br
Guillain
